# This workflow will install Maven and run the build on Ubuntu

name: Maven Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'ubuntu-latest'
      - name: Build with Maven
        run: mvn clean install